inherit_from: configs/ReplicaMultiagent/replica_multiagent.yaml
config_path: configs/ReplicaMultiagent/apart_2.yaml
data:
  frame_limit: 2500
  scene_name: apart_2
  input_path: ReplicaMultiagent/Apart-2/
  output_path: output/CP-SLAM_dataset/Apart-2/